version: 2

sources:
  - name: financial_risk_staging
    dataset: staging
    tables:
      - name: customers
      - name: merchants
      - name: accounts
      - name: devices

  - name: financial_risk_analytics
    dataset: analytics
    tables:
      - name: transaction_risk
